import RcpRclmFormalCoreV4

#print axioms RcpRclmFormalCoreV4.Autonomous.autonomous_accepted_step_sound
#print axioms RcpRclmFormalCoreV4.Autonomous.recursive_productivity_retained
#print axioms RcpRclmFormalCoreV4.Autonomous.recursive_productivity_strictly_expands_when_witnessed
#print axioms RcpRclmFormalCoreV4.Autonomous.firstAccepted_sound
#print axioms RcpRclmFormalCoreV4.Autonomous.firstAccepted_none
#print axioms RcpRclmFormalCoreV4.Autonomous.bounded_search_complete
#print axioms RcpRclmFormalCoreV4.Autonomous.search_exhaustion_sound
#print axioms RcpRclmFormalCoreV4.Autonomous.nonstagnation_or_certified_exhaustion
#print axioms RcpRclmFormalCoreV4.Autonomous.finite_autonomous_frontier_growth
#print axioms RcpRclmFormalCoreV4.Autonomous.finite_recursive_productivity_retained
#print axioms RcpRclmFormalCoreV4.Autonomous.finite_autonomous_resource_bound
#print axioms RcpRclmFormalCoreV4.Autonomous.constructive_successor_availability_on_declared_class
#print axioms RcpRclmFormalCoreV4.Autonomous.conditional_infinite_autonomous_rclm_trajectory_exists
