import RcpRclmFormalCoreV2.MainTheorem

#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.klDivergence_nonnegative
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.klDivergence_self
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.uniformBinary_kl_biasedBinary
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.uniformBinary_kl_biasedBinary_pos
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.shannonEntropy_extendByZero
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.klDivergence_extendByZero
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.recover_extendByZero
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.conservative_extension_recovery
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryCheck_eq_true_iff
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryCheck_rejects_invalidCandidate
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryStateDistance_triangle
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.initial_improvement_obligations
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.target_stability_obligations
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binary_checker_refines_kernel
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryLyapunov_motion_step
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryUnsupportedCollapse_step
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryRelevance_step
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryWorkedTrajectory_first_step_strict
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryWorkedTrajectory_endpoint_recovery
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryWorkedTrajectory_lyapunov_motion_bound
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryWorkedTrajectory_ambiguity_bound
#print axioms RcpRclmFormalCoreV2.RCP.ClassicalFinite.binaryWorkedTrajectory_relevance_bound