name = "rcp_rclm_formal_core_v2"
version = "0.1.0"
defaultTargets = ["RcpRclmFormalCoreV2"]

[[lean_lib]]
name = "RcpRclmFormalCoreV2"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "fabf563a7c95a166b8d7b6efca11c8b4dc9d911f"
